[package]
name = "witx-generate-raw"
version = "0.0.1"
publish = false
authors = ["The Cranelift Project Developers"]
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
edition = "2018"

[dependencies]
heck = "0.3"
witx = "0.8"
cfg-if = "0.1"

[features]
default = []
multi-module = []
